#!/bin/bash

touch state.yaml

docker run --rm -it \
    --name eve-fuelbot \
    --volume "$(pwd)"/test-config.yaml:/app/foo.yaml:ro \
    --volume "$(pwd)"/test-state.yaml:/app/state.yaml \
    boravyvorant/eve-fuelbot foo.yaml
